#!/usr/bin/env ruby

require_relative "./lib/reminder"
require_relative "./lib/system_state"

exit if SystemState.idle_time > 600

tip = ARGV[0]
unless tip
  tip_root = File.join File.dirname(__FILE__), "./reminders/**/*.txt"
  all_tips = Dir[tip_root]
  tip = all_tips.shuffle.first
end

if tip
  Reminder.from_file(tip).display
end


